// layout.js or _app.js depending on your setup
"use client";
import { Provider } from "react-redux";
import { PersistGate } from 'redux-persist/integration/react';
import { Inter } from "next/font/google";
import MyntraStore, { persistor } from "@/store";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Myntra</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <Provider store={MyntraStore}>
          <PersistGate loading={null} persistor={persistor}>
            {children}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
