"use client";
import { Provider } from "react-redux";
import { Inter } from "next/font/google";
import MyntraStore from "@/store";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Myntra</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <Provider store={MyntraStore}>{children}</Provider>
      </body>
    </html>
  );
}
